<a href="https://colab.research.google.com/github/Karthik5412/Deep-Learning-Projects/blob/main/ANN%20Model/notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import pandas as pd
import numpy as np

In [48]:
df = pd.read_csv('/content/zomato.csv', engine= 'python', on_bad_lines='skip')

df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [49]:
print(df.shape)
df.isna().sum()

(51155, 17)

url                                0
address                            0
name                               0
online_order                       0
book_table                         0
rate                            7775
votes                              0
phone                           1203
location                          21
rest_type                        224
dish_liked                     28074
cuisines                          45
approx_cost(for two people)      344
reviews_list                       0
menu_item                          0
listed_in(type)                    0
listed_in(city)                    0
dtype: int64

In [50]:
df = df.dropna()
df.isna().sum()

url                            0
address                        0
name                           0
online_order                   0
book_table                     0
rate                           0
votes                          0
phone                          0
location                       0
rest_type                      0
dish_liked                     0
cuisines                       0
approx_cost(for two people)    0
reviews_list                   0
menu_item                      0
listed_in(type)                0
listed_in(city)                0
dtype: int64

In [51]:
print(df.columns)
unwanted_cols = ['menu_item','phone']

df= df.drop(columns=unwanted_cols)

df.head(2)

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

,url,address,name,online_order,book_table,rate,votes,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",Buffet,Banashankari

In [52]:
df.loc[1,'dish_liked']

'Momos, Lunch Buffet, Chocolate Nirvana, Thai Green Curry, Paneer Tikka, Dum Biryani, Chicken Biryani'

In [53]:
df['total address'] = df['address'] + ', ' +df['location'] + ', ' +  df['listed_in(city)']
df['food items'] = df['dish_liked'] + ', ' +df['cuisines']
original_df = df.copy()

df = df[['listed_in(type)','food items', 'rest_type','total address','book_table','online_order', 'rate', 'approx_cost(for two people)']]
df.head(2)

,listed_in(type),food items,rest_type,total address,book_table,online_order,rate,approx_cost(for two people)
0,Buffet,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",Casual Dining,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,800
1,Buffet,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",Casual Dining,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",No,Yes,4.1/5,800

In [54]:
df.to_csv('cleaned_df.csv')

In [55]:
from nltk.tag.brill import Word
import re
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

nltk.download('stopwords')
nltk.download('wordnet')

stop_words = set(stopwords.words('english'))
lematizer = WordNetLemmatizer()

def preprocessing_data (text) -> str:

    text = str(text)
    # Converting the text into lower case
    text = text.lower()

    # Removing punctuvations
    text = re.sub(r'[^a-zA-Z0-9\s]','',text)

    # Removing stop words
    words = [w for w in text.split() if w not in stop_words]

    # Lemotization
    words = [lematizer.lemmatize(w) for w in words]

    return ' '.join(words)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [56]:
df['total address'] = ' - ' + df['total address']
df['total address'] = df['total address'].apply(preprocessing_data)
df.head(2)

,listed_in(type),food items,rest_type,total address,book_table,online_order,rate,approx_cost(for two people)
0,Buffet,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",Casual Dining,942 21st main road 2nd stage banashankari bang...,Yes,Yes,4.1/5,800
1,Buffet,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",Casual Dining,2nd floor 80 foot road near big bazaar 6th blo...,No,Yes,4.1/5,800

In [57]:
df.loc[df['rate'] == 'NEW','rate'] = df['rate'].mode()[0]
df['rate'].unique()

array(['4.1/5', '3.8/5', '3.7/5', '4.6/5', '4.0/5', '4.2/5', '3.9/5',
       '3.0/5', '3.6/5', '2.8/5', '4.4/5', '3.1/5', '4.3/5', '2.6/5',
       '3.3/5', '3.5/5', '3.8 /5', '3.2/5', '4.5/5', '2.5/5', '2.9/5',
       '3.4/5', '2.7/5', '4.7/5', '2.4/5', '2.2/5', '2.3/5', '4.8/5',
       '3.9 /5', '4.2 /5', '4.0 /5', '4.1 /5', '2.9 /5', '2.7 /5',
       '2.5 /5', '2.6 /5', '4.5 /5', '4.3 /5', '3.7 /5', '4.4 /5',
       '4.9/5', '2.1/5', '2.0/5', '1.8/5', '3.4 /5', '3.6 /5', '3.3 /5',
       '4.6 /5', '4.9 /5', '3.2 /5', '3.0 /5', '2.8 /5', '3.5 /5',
       '3.1 /5', '4.8 /5', '2.3 /5', '2.4 /5', '4.7 /5', '2.2 /5',
       '2.0 /5', '2.1 /5', '1.8 /5'], dtype=object)

In [58]:
df['rate'] = df['rate'].apply(lambda x: x.replace('/5','')).str.strip().astype('float')
df['book_table'] = df['book_table'].map({'Yes': 1, 'No': 0}).astype('int')
df['online_order'] = df['online_order'].map({'Yes': 1, 'No': 0}).astype('int')
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22643 entries, 0 to 51153
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   listed_in(type)              22643 non-null  object
 1   food items                   22643 non-null  object
 2   rest_type                    22643 non-null  object
 3   total address                22643 non-null  object
 4   book_table                   22643 non-null  int64
 5   online_order                 22643 non-null  int64
 6   rate                         22643 non-null  float64
 7   approx_cost(for two people)  22643 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 2.1+ MB

In [59]:
df.head(2)

,listed_in(type),food items,rest_type,total address,book_table,online_order,rate,approx_cost(for two people)
0,Buffet,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",Casual Dining,942 21st main road 2nd stage banashankari bang...,1,1,4.1,800
1,Buffet,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",Casual Dining,2nd floor 80 foot road near big bazaar 6th blo...,0,1,4.1,800

In [60]:
df['rest_type'] = df['rest_type'].apply(preprocessing_data)
df['food items'] = df['food items'].apply(preprocessing_data)

df.head(2)

,listed_in(type),food items,rest_type,total address,book_table,online_order,rate,approx_cost(for two people)
0,Buffet,pasta lunch buffet masala papad paneer lajawab...,casual dining,942 21st main road 2nd stage banashankari bang...,1,1,4.1,800
1,Buffet,momos lunch buffet chocolate nirvana thai gree...,casual dining,2nd floor 80 foot road near big bazaar 6th blo...,0,1,4.1,800

In [61]:
df['approx_cost(for two people)'] = df['approx_cost(for two people)'].apply(lambda x: x.replace(',', '')).astype(float)

In [62]:
df['listed_in(type)'] = df['listed_in(type)'].replace('Drinks & nightlife' , 'Drinks and Nightlife')
df['listed_in(type)'].unique()

array(['Buffet', 'Cafes', 'Delivery', 'Desserts', 'Dine-out',
       'Drinks and Nightlife', 'Pubs and bars'], dtype=object)

In [63]:
df.head()

,listed_in(type),food items,rest_type,total address,book_table,online_order,rate,approx_cost(for two people)
0,Buffet,pasta lunch buffet masala papad paneer lajawab...,casual dining,942 21st main road 2nd stage banashankari bang...,1,1,4.1,800.0
1,Buffet,momos lunch buffet chocolate nirvana thai gree...,casual dining,2nd floor 80 foot road near big bazaar 6th blo...,0,1,4.1,800.0
2,Buffet,churros cannelloni minestrone soup hot chocola...,cafe casual dining,1112 next kims medical college 17th cross 2nd ...,0,1,3.8,800.0
3,Buffet,masala dosa south indian north indian,quick bite,1st floor annakuteera 3rd stage banashankari b...,0,0,3.7,300.0
4,Buffet,panipuri gol gappe north indian rajasthani,casual dining,10 3rd floor lakshmi associate gandhi bazaar m...,0,0,3.8,600.0

In [64]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

In [65]:
df['listed_in(type)'] = label_encoder.fit_transform(df['listed_in(type)'])
df.head(2)

,listed_in(type),food items,rest_type,total address,book_table,online_order,rate,approx_cost(for two people)
0,0,pasta lunch buffet masala papad paneer lajawab...,casual dining,942 21st main road 2nd stage banashankari bang...,1,1,4.1,800.0
1,0,momos lunch buffet chocolate nirvana thai gree...,casual dining,2nd floor 80 foot road near big bazaar 6th blo...,0,1,4.1,800.0

In [66]:
df['final_phrase'] = df['food items'] + ' ' +df['rest_type'] + ' ' + df['total address']

df.head(2)

,listed_in(type),food items,rest_type,total address,book_table,online_order,rate,approx_cost(for two people),final_phrase
0,0,pasta lunch buffet masala papad paneer lajawab...,casual dining,942 21st main road 2nd stage banashankari bang...,1,1,4.1,800.0,pasta lunch buffet masala papad paneer lajawab...
1,0,momos lunch buffet chocolate nirvana thai gree...,casual dining,2nd floor 80 foot road near big bazaar 6th blo...,0,1,4.1,800.0,momos lunch buffet chocolate nirvana thai gree...

In [67]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features= 1000)

tfidf_matrix = tfidf.fit_transform(df['final_phrase']).toarray()

In [69]:
from sklearn.preprocessing import StandardScaler

four_scaler = StandardScaler()
one_scaler = StandardScaler()

cost_matrix = four_scaler.fit_transform(df.drop(columns= ['rest_type','rate', 'total address','food items','final_phrase']))

rate_array = one_scaler.fit_transform(df['rate'].values.reshape(-1, 1))

In [70]:
final_matrix = np.hstack((tfidf_matrix, cost_matrix))

final_matrix

array([[ 0.        ,  0.        ,  0.        , ...,  1.69760978,
         0.63941198,  0.101789  ],
       [ 0.        ,  0.        ,  0.        , ..., -0.58906352,
         0.63941198,  0.101789  ],
       [ 0.        ,  0.        ,  0.        , ..., -0.58906352,
         0.63941198,  0.101789  ],
       ...,
       [ 0.        ,  0.        ,  0.        , ..., -0.58906352,
        -1.56393691,  0.8728471 ],
       [ 0.        ,  0.        ,  0.        , ..., -0.58906352,
        -1.56393691,  0.101789  ],
       [ 0.        ,  0.        ,  0.        , ...,  1.69760978,
        -1.56393691,  3.37878593]])

In [71]:
df.loc[0:3, ['final_phrase','listed_in(type)', 'book_table', 'online_order', 'approx_cost(for two people)']]

,final_phrase,listed_in(type),book_table,online_order,approx_cost(for two people)
0,pasta lunch buffet masala papad paneer lajawab...,0,1,1,800.0
1,momos lunch buffet chocolate nirvana thai gree...,0,0,1,800.0
2,churros cannelloni minestrone soup hot chocola...,0,0,1,800.0
3,masala dosa south indian north indian quick bi...,0,0,0,300.0

In [72]:
final_matrix[0:3]

array([[ 0.        ,  0.        ,  0.        , ...,  1.69760978,
         0.63941198,  0.101789  ],
       [ 0.        ,  0.        ,  0.        , ..., -0.58906352,
         0.63941198,  0.101789  ],
       [ 0.        ,  0.        ,  0.        , ..., -0.58906352,
         0.63941198,  0.101789  ]])

In [73]:
rate_array

array([[ 0.48277702],
       [ 0.48277702],
       [-0.23315199],
       ...,
       [-2.61958201],
       [-3.33551102],
       [ 0.96006302]])

In [74]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [75]:
network = keras.Sequential([
    layers.Dense(256, activation='relu',input_dim=final_matrix.shape[1]),
    layers.Dropout(0.3),
    layers.Dense(128, activation='relu'),
    layers.Dense(64, activation='swish'),
    layers.Dense(1, activation='linear')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [76]:
network.compile(optimizer='adam', loss='mean_squared_error', metrics= ['mae'])

In [77]:
history =network.fit(final_matrix, rate_array, epochs= 150, batch_size=400, validation_split=0.2, verbose= 1)

Epoch 1/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.7231 - mae: 0.6035 - val_loss: 0.6332 - val_mae: 0.5612
Epoch 2/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.4556 - mae: 0.4821 - val_loss: 0.5063 - val_mae: 0.4922
Epoch 3/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.3125 - mae: 0.3938 - val_loss: 0.3967 - val_mae: 0.4341
Epoch 4/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.2131 - mae: 0.3220 - val_loss: 0.3143 - val_mae: 0.3807
Epoch 5/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 0.1479 - mae: 0.2699 - val_loss: 0.2756 - val_mae: 0.3504
Epoch 6/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.1100 - mae: 0.2348 - val_loss: 0.2420 - val_mae: 0.3173
Epoch 7/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.0865 - mae: 0.2106 - val_loss: 0.2252 - val_mae: 0.3009
Epoch 8/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0724 - mae: 0.1940 - val_loss: 0.2107 - val_mae: 0.2861
Epoch 9/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0638 - mae: 0.1818 - val_loss: 0.1973 - val_mae: 0.2673
Epoch 10/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0585 - mae: 0.1745 - val_loss: 0.1925 - val_mae: 0.2656
Epoch 11/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0501 - mae: 0.1616 - val_loss: 0.1866 - val_mae: 0.2557
Epoch 12/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0464 - mae: 0.1563 - val_loss: 0.1858 - val_mae: 0.2525
Epoch 13/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0436 - mae: 0.1527 - val_loss: 0.1852 - val_mae: 0.2501
Epoch 14/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0391 - mae: 0.1431 - val_loss: 0.1780 - val_mae: 0.2412
Epoch 15/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0370 - mae: 0.1405 - val_loss: 0.1797 - val_mae: 0.2397
Epoch 16/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0347 - mae: 0.1360 - val_loss: 0.1769 - val_mae: 0.2384
Epoch 17/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.0335 - mae: 0.1327 - val_loss: 0.1781 - val_mae: 0.2412
Epoch 18/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0316 - mae: 0.1294 - val_loss: 0.1758 - val_mae: 0.2363
Epoch 19/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0302 - mae: 0.1268 - val_loss: 0.1703 - val_mae: 0.2296
Epoch 20/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0287 - mae: 0.1240 - val_loss: 0.1736 - val_mae: 0.2351
Epoch 21/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0288 - mae: 0.1235 - val_loss: 0.1691 - val_mae: 0.2269
Epoch 22/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0264 - mae: 0.1191 - val_loss: 0.1744 - val_mae: 0.2261
Epoch 23/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0260 - mae: 0.1178 - val_loss: 0.1725 - val_mae: 0.2295
Epoch 24/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0242 - mae: 0.1139 - val_loss: 0.1682 - val_mae: 0.2223
Epoch 25/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0235 - mae: 0.1120 - val_loss: 0.1686 - val_mae: 0.2231
Epoch 26/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0233 - mae: 0.1112 - val_loss: 0.1675 - val_mae: 0.2177
Epoch 27/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0232 - mae: 0.1107 - val_loss: 0.1680 - val_mae: 0.2244
Epoch 28/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0231 - mae: 0.1104 - val_loss: 0.1658 - val_mae: 0.2233
Epoch 29/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0215 - mae: 0.1080 - val_loss: 0.1652 - val_mae: 0.2219
Epoch 30/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 0.0214 - mae: 0.1067 - val_loss: 0.1634 - val_mae: 0.2183
Epoch 31/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0205 - mae: 0.1048 - val_loss: 0.1639 - val_mae: 0.2149
Epoch 32/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0197 - mae: 0.1020 - val_loss: 0.1645 - val_mae: 0.2165
Epoch 33/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0192 - mae: 0.1012 - val_loss: 0.1672 - val_mae: 0.2189
Epoch 34/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0196 - mae: 0.1025 - val_loss: 0.1639 - val_mae: 0.2160
Epoch 35/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0186 - mae: 0.0994 - val_loss: 0.1653 - val_mae: 0.2159
Epoch 36/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0186 - mae: 0.0997 - val_loss: 0.1657 - val_mae: 0.2157
Epoch 37/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0184 - mae: 0.0987 - val_loss: 0.1630 - val_mae: 0.2144
Epoch 38/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0173 - mae: 0.0959 - val_loss: 0.1611 - val_mae: 0.2140
Epoch 39/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0174 - mae: 0.0963 - val_loss: 0.1642 - val_mae: 0.2155
Epoch 40/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0168 - mae: 0.0946 - val_loss: 0.1642 - val_mae: 0.2138
Epoch 41/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0165 - mae: 0.0942 - val_loss: 0.1616 - val_mae: 0.2088
Epoch 42/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0166 - mae: 0.0939 - val_loss: 0.1632 - val_mae: 0.2143
Epoch 43/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0167 - mae: 0.0941 - val_loss: 0.1621 - val_mae: 0.2100
Epoch 44/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0163 - mae: 0.0929 - val_loss: 0.1601 - val_mae: 0.2101
Epoch 45/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0157 - mae: 0.0912 - val_loss: 0.1629 - val_mae: 0.2149
Epoch 46/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0153 - mae: 0.0898 - val_loss: 0.1651 - val_mae: 0.2129
Epoch 47/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0152 - mae: 0.0900 - val_loss: 0.1619 - val_mae: 0.2125
Epoch 48/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0152 - mae: 0.0896 - val_loss: 0.1634 - val_mae: 0.2119
Epoch 49/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0146 - mae: 0.0883 - val_loss: 0.1603 - val_mae: 0.2095
Epoch 50/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0148 - mae: 0.0883 - val_loss: 0.1620 - val_mae: 0.2106
Epoch 51/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0144 - mae: 0.0875 - val_loss: 0.1590 - val_mae: 0.2091
Epoch 52/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0143 - mae: 0.0872 - val_loss: 0.1617 - val_mae: 0.2098
Epoch 53/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0143 - mae: 0.0869 - val_loss: 0.1589 - val_mae: 0.2107
Epoch 54/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0142 - mae: 0.0866 - val_loss: 0.1613 - val_mae: 0.2065
Epoch 55/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0137 - mae: 0.0848 - val_loss: 0.1612 - val_mae: 0.2101
Epoch 56/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0138 - mae: 0.0853 - val_loss: 0.1588 - val_mae: 0.2082
Epoch 57/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0133 - mae: 0.0839 - val_loss: 0.1616 - val_mae: 0.2061
Epoch 58/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0131 - mae: 0.0833 - val_loss: 0.1600 - val_mae: 0.2124
Epoch 59/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0128 - mae: 0.0826 - val_loss: 0.1579 - val_mae: 0.2039
Epoch 60/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0129 - mae: 0.0824 - val_loss: 0.1597 - val_mae: 0.2065
Epoch 61/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0125 - mae: 0.0810 - val_loss: 0.1596 - val_mae: 0.2066
Epoch 62/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0126 - mae: 0.0817 - val_loss: 0.1596 - val_mae: 0.2108
Epoch 63/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0123 - mae: 0.0809 - val_loss: 0.1566 - val_mae: 0.2065
Epoch 64/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0126 - mae: 0.0811 - val_loss: 0.1592 - val_mae: 0.2067
Epoch 65/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0123 - mae: 0.0802 - val_loss: 0.1560 - val_mae: 0.2024
Epoch 66/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0124 - mae: 0.0814 - val_loss: 0.1593 - val_mae: 0.2042
Epoch 67/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0119 - mae: 0.0792 - val_loss: 0.1566 - val_mae: 0.2012
Epoch 68/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0791 - val_loss: 0.1610 - val_mae: 0.2045
Epoch 69/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0117 - mae: 0.0783 - val_loss: 0.1585 - val_mae: 0.2089
Epoch 70/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0116 - mae: 0.0775 - val_loss: 0.1576 - val_mae: 0.2078
Epoch 71/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0114 - mae: 0.0775 - val_loss: 0.1568 - val_mae: 0.2066
Epoch 72/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0112 - mae: 0.0769 - val_loss: 0.1575 - val_mae: 0.2021
Epoch 73/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0112 - mae: 0.0764 - val_loss: 0.1563 - val_mae: 0.2024
Epoch 74/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0114 - mae: 0.0772 - val_loss: 0.1565 - val_mae: 0.2049
Epoch 75/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0113 - mae: 0.0770 - val_loss: 0.1566 - val_mae: 0.1988
Epoch 76/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0108 - mae: 0.0754 - val_loss: 0.1561 - val_mae: 0.2014
Epoch 77/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0107 - mae: 0.0753 - val_loss: 0.1597 - val_mae: 0.2022
Epoch 78/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0107 - mae: 0.0749 - val_loss: 0.1551 - val_mae: 0.2004
Epoch 79/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0105 - mae: 0.0741 - val_loss: 0.1562 - val_mae: 0.2004
Epoch 80/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 0.0108 - mae: 0.0752 - val_loss: 0.1566 - val_mae: 0.2055
Epoch 81/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0105 - mae: 0.0742 - val_loss: 0.1559 - val_mae: 0.2031
Epoch 82/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0106 - mae: 0.0740 - val_loss: 0.1581 - val_mae: 0.2096
Epoch 83/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0109 - mae: 0.0748 - val_loss: 0.1595 - val_mae: 0.2109
Epoch 84/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0104 - mae: 0.0733 - val_loss: 0.1551 - val_mae: 0.2025
Epoch 85/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0098 - mae: 0.0717 - val_loss: 0.1531 - val_mae: 0.1981
Epoch 86/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0102 - mae: 0.0730 - val_loss: 0.1585 - val_mae: 0.1991
Epoch 87/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0101 - mae: 0.0722 - val_loss: 0.1546 - val_mae: 0.1984
Epoch 88/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0099 - mae: 0.0714 - val_loss: 0.1540 - val_mae: 0.2014
Epoch 89/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0101 - mae: 0.0719 - val_loss: 0.1586 - val_mae: 0.2035
Epoch 90/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0098 - mae: 0.0710 - val_loss: 0.1565 - val_mae: 0.2044
Epoch 91/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 0.0097 - mae: 0.0708 - val_loss: 0.1572 - val_mae: 0.2052
Epoch 92/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 0.0098 - mae: 0.0711 - val_loss: 0.1549 - val_mae: 0.2057
Epoch 93/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0096 - mae: 0.0711 - val_loss: 0.1541 - val_mae: 0.1990
Epoch 94/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0096 - mae: 0.0696 - val_loss: 0.1546 - val_mae: 0.1977
Epoch 95/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0096 - mae: 0.0705 - val_loss: 0.1560 - val_mae: 0.1949
Epoch 96/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0092 - mae: 0.0692 - val_loss: 0.1559 - val_mae: 0.2020
Epoch 97/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0095 - mae: 0.0702 - val_loss: 0.1570 - val_mae: 0.2036
Epoch 98/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0092 - mae: 0.0682 - val_loss: 0.1559 - val_mae: 0.1987
Epoch 99/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0090 - mae: 0.0682 - val_loss: 0.1587 - val_mae: 0.2007
Epoch 100/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0088 - mae: 0.0677 - val_loss: 0.1595 - val_mae: 0.2013
Epoch 101/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0089 - mae: 0.0676 - val_loss: 0.1545 - val_mae: 0.1957
Epoch 102/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0091 - mae: 0.0680 - val_loss: 0.1550 - val_mae: 0.1973
Epoch 103/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0085 - mae: 0.0661 - val_loss: 0.1560 - val_mae: 0.1988
Epoch 104/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0089 - mae: 0.0670 - val_loss: 0.1587 - val_mae: 0.2025
Epoch 105/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0087 - mae: 0.0670 - val_loss: 0.1558 - val_mae: 0.1955
Epoch 106/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0086 - mae: 0.0669 - val_loss: 0.1565 - val_mae: 0.1988
Epoch 107/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0089 - mae: 0.0674 - val_loss: 0.1563 - val_mae: 0.1970
Epoch 108/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0087 - mae: 0.0669 - val_loss: 0.1559 - val_mae: 0.1944
Epoch 109/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0085 - mae: 0.0659 - val_loss: 0.1554 - val_mae: 0.1967
Epoch 110/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0088 - mae: 0.0676 - val_loss: 0.1543 - val_mae: 0.1972
Epoch 111/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0086 - mae: 0.0661 - val_loss: 0.1563 - val_mae: 0.1967
Epoch 112/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0087 - mae: 0.0665 - val_loss: 0.1540 - val_mae: 0.1970
Epoch 113/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0083 - mae: 0.0652 - val_loss: 0.1552 - val_mae: 0.1955
Epoch 114/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0083 - mae: 0.0650 - val_loss: 0.1550 - val_mae: 0.1987
Epoch 115/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step - loss: 0.0084 - mae: 0.0651 - val_loss: 0.1559 - val_mae: 0.1962
Epoch 116/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0080 - mae: 0.0645 - val_loss: 0.1548 - val_mae: 0.1981
Epoch 117/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0080 - mae: 0.0641 - val_loss: 0.1542 - val_mae: 0.1940
Epoch 118/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0084 - mae: 0.0648 - val_loss: 0.1552 - val_mae: 0.1981
Epoch 119/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0084 - mae: 0.0654 - val_loss: 0.1547 - val_mae: 0.1948
Epoch 120/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0082 - mae: 0.0647 - val_loss: 0.1535 - val_mae: 0.1945
Epoch 121/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0080 - mae: 0.0641 - val_loss: 0.1542 - val_mae: 0.1925
Epoch 122/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0079 - mae: 0.0634 - val_loss: 0.1540 - val_mae: 0.1994
Epoch 123/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0081 - mae: 0.0645 - val_loss: 0.1550 - val_mae: 0.1942
Epoch 124/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0078 - mae: 0.0628 - val_loss: 0.1555 - val_mae: 0.2017
Epoch 125/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0076 - mae: 0.0624 - val_loss: 0.1545 - val_mae: 0.1954
Epoch 126/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0074 - mae: 0.0616 - val_loss: 0.1563 - val_mae: 0.1984
Epoch 127/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0076 - mae: 0.0626 - val_loss: 0.1542 - val_mae: 0.1925
Epoch 128/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.0078 - mae: 0.0631 - val_loss: 0.1540 - val_mae: 0.1927
Epoch 129/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0075 - mae: 0.0617 - val_loss: 0.1550 - val_mae: 0.1961
Epoch 130/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0074 - mae: 0.0610 - val_loss: 0.1546 - val_mae: 0.1954
Epoch 131/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0074 - mae: 0.0611 - val_loss: 0.1553 - val_mae: 0.1921
Epoch 132/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0075 - mae: 0.0615 - val_loss: 0.1565 - val_mae: 0.1946
Epoch 133/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0075 - mae: 0.0622 - val_loss: 0.1542 - val_mae: 0.1973
Epoch 134/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0070 - mae: 0.0601 - val_loss: 0.1569 - val_mae: 0.1982
Epoch 135/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0073 - mae: 0.0611 - val_loss: 0.1546 - val_mae: 0.1928
Epoch 136/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0073 - mae: 0.0609 - val_loss: 0.1554 - val_mae: 0.1946
Epoch 137/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0073 - mae: 0.0609 - val_loss: 0.1537 - val_mae: 0.1921
Epoch 138/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0071 - mae: 0.0601 - val_loss: 0.1542 - val_mae: 0.1889
Epoch 139/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.0070 - mae: 0.0598 - val_loss: 0.1540 - val_mae: 0.1895
Epoch 140/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step - loss: 0.0070 - mae: 0.0593 - val_loss: 0.1541 - val_mae: 0.1925
Epoch 141/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0073 - mae: 0.0604 - val_loss: 0.1525 - val_mae: 0.1910
Epoch 142/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0071 - mae: 0.0600 - val_loss: 0.1546 - val_mae: 0.1951
Epoch 143/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0067 - mae: 0.0583 - val_loss: 0.1545 - val_mae: 0.1897
Epoch 144/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0067 - mae: 0.0583 - val_loss: 0.1538 - val_mae: 0.1876
Epoch 145/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0069 - mae: 0.0592 - val_loss: 0.1554 - val_mae: 0.1977
Epoch 146/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0068 - mae: 0.0584 - val_loss: 0.1550 - val_mae: 0.1930
Epoch 147/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0069 - mae: 0.0588 - val_loss: 0.1536 - val_mae: 0.1962
Epoch 148/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0067 - mae: 0.0583 - val_loss: 0.1525 - val_mae: 0.1906
Epoch 149/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0068 - mae: 0.0586 - val_loss: 0.1539 - val_mae: 0.1913
Epoch 150/150
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0068 - mae: 0.0586 - val_loss: 0.1541 - val_mae: 0.1996

In [78]:
network.save('network.keras')

In [79]:
import joblib

joblib.dump(four_scaler, 'four_scaler.plk')
joblib.dump(one_scaler, 'one_scaler.plk')
joblib.dump(tfidf, 'tfidf.plk')
joblib.dump(label_encoder, 'label_encoder.plk')

['label_encoder.plk']